version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: 'no'
    environment:
      #设置root帐号密码
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    volumes:
      # win
      - D:/zyr/code/data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - D:/zyr/code/data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - D:/zyr/code/log/mysql/log:/var/log/mysql #日志文件挂载
      # linux
      # - /data/mysql/data/db:/var/lib/mysql #数据文件挂载
      # - /data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      # - /log/mysql/log:/var/log/mysql #日志文件挂载
  # mq消息服务
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    restart: 'no'
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      # win
      - D:/zyr/code/data/rabbitmq/data:/var/lib/rabbitmq
      - D:/zyr/code/log/rabbitmq/log:/var/log/rabbitmq
      # linux
      # - /data/rabbitmq/data:/var/lib/rabbitmq
      # - /log/rabbitmq/log:/var/log/rabbitmq
  # 代理服务
  nginx:
    image: nginx:1.22
    container_name: nginx
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - 80:80
    volumes:
      # win
      - D:/zyr/code/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - D:/zyr/code/data/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - D:/zyr/code/log/nginx/log:/var/log/nginx #日志文件挂载
      # linux
      # - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      # - /data/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      # - /log/nginx/log:/var/log/nginx #日志文件挂载
  # 缓存服务
  redis:
    image: redis:7
    container_name: redis
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - 6379:6379 
    command: redis-server --appendonly yes
    volumes:
      # win
      - D:/zyr/code/data/redis/data:/data
      # linux
      # - /data/redis/data:/data
  # 微服务注册中心
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-registry
    restart: 'no'
    environment:
      - "MODE=standalone"
    ports:
      - 8848:8848
  # nosql数据库    
  mongo-db:
    image: 'mongo:5.0'
    container_name: "mongo-db"
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      # win
      - D:/zyr/code/data/mongodb:/data/db
      #linux
      # - /data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbUsername
      MONGO_INITDB_ROOT_PASSWORD: mongodbPassword
      MONGO_INITDB_DATABASE: mongoDatabase
  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins"
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    user: root
    privileged: true
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      # win
      - jenkins_home:/var/jenkins_home # 保存Jenkins的数据持久化
      - D:/mall-swarm:/usr/local/mall-swarm 
      - D:/zyr/dev/apache-maven-3.9.6:/usr/local/apache-maven-3.9.6
      - D:/zyr/dev/jdk1.8.0_181:/usr/local/jdk1.8.0_181
      #linux
      # - /data/jenkins/code:/usr/local
volumes:
  mongodb: {}
  jenkins_home: {}