version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: 'no'
    environment:
      #设置root帐号密码
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    volumes:
      # win
      # - D:/zyr/code/data/mysql/data/db:/var/lib/mysql #数据文件挂载
      # - D:/zyr/code/data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      # - D:/zyr/code/log/mysql/log:/var/log/mysql #日志文件挂载
      # linux
      - /data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /log/mysql/log:/var/log/mysql #日志文件挂载
  # mq消息服务
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    restart: 'no'
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      # win
      # - D:/zyr/code/data/rabbitmq/data:/var/lib/rabbitmq
      # - D:/zyr/code/log/rabbitmq/log:/var/log/rabbitmq
      # linux
      - /data/rabbitmq/data:/var/lib/rabbitmq
      - /log/rabbitmq/log:/var/log/rabbitmq
  # nginx代理服务mariadb数据库
  nginx-db:
    image: 'jc21/mariadb-aria:10.11.5'
    container_name: "nginx-db"
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      # win
      # - D:/zyr/code/data/nginx-db/mysql:/var/lib/mysql
      # linux
      - /data/nginx-db/mysql:/var/lib/mysql
  # 代理服务
  nginx-manage:
    image: 'jc21/nginx-proxy-manager:2'
    container_name: nginx-manage
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      # win
      # - D:/zyr/code/data/nginx-manage/data:/data
      # - D:/zyr/code/data/nginx-manage/letsencrypt:/etc/letsencrypt
      # linux
      - /data/nginx-manage/data:/data
      - /data/nginx-manage/letsencrypt:/etc/letsencrypt
    links:
      - nginx-db
    depends_on:
      - nginx-db
  # 缓存服务
  redis:
    image: redis:7
    container_name: redis
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    ports:
      - 6379:6379 
    command: redis-server --appendonly yes
    volumes:
      # win
      # - D:/zyr/code/data/redis/data:/data
      # linux
      - /data/redis/data:/data
  # 微服务注册中心
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-registry
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    environment:
      - MODE=standalone
      # JVM调优参数
      - JVM_XMS=128m   #-Xms default :2g
      - JVM_XMX=128m   #-Xmx default :2g
      - JVM_XMN=32m   #-Xmn default :1g
      - JVM_MS=8m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=8m    #-XX:MaxMetaspaceSize default :320m
      - NACOS_DEBUG=n #是否开启远程debug，y/n，默认n
      - TOMCAT_ACCESSLOG_ENABLED=false #是否开始tomcat访问日志的记录，默认false
    ports:
      - 8848:8848
  # nosql数据库    
  mongo-db:
    image: 'mongo:5.0'
    container_name: "mongo-db"
    restart: 'no'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      # win
      # - D:/zyr/code/data/mongodb:/data/db
      #linux
      - /data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbUsername
      MONGO_INITDB_ROOT_PASSWORD: mongodbPassword
      MONGO_INITDB_DATABASE: mongoDatabase
volumes:
  mongodb: {}